<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Nav" failures="1" tests="3" name="Test" time="51.321" errors="0" timestamp="2023-01-19T13:25:54 EST">
  <testcase classname="com.naveenautomation.Tests.AccountCreatedTest" name="verifyUserIsAbleToSignUpSuccesfully" time="2.066">
    <skipped/>
  </testcase> <!-- verifyUserIsAbleToSignUpSuccesfully -->
  <testcase classname="com.naveenautomation.Tests.AccountCreatedTest" name="verifyUserIsAbleToSignUpSuccesfully" time="2.017">
    <skipped/>
  </testcase> <!-- verifyUserIsAbleToSignUpSuccesfully -->
  <testcase classname="com.naveenautomation.Tests.AccountCreatedTest" name="verifyUserIsAbleToSignUpSuccesfully" time="1.77">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Sign up failed expected [Your Account Has Been Created!] but found [Register Account]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]
at com.naveenautomation.Tests.AccountCreatedTest.verifyUserIsAbleToSignUpSuccesfully(AccountCreatedTest.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserIsAbleToSignUpSuccesfully -->
</testsuite> <!-- Test -->
